# Generated by Django 4.2 on 2023-04-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchiveTenders',
            new_name='ArchiveTender',
        ),
    ]
