# Generated by Django 4.2 on 2023-04-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_customer_dknumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivetender',
            name='publication_date',
            field=models.DateField(null=True),
        ),
    ]
