# Generated by Django 4.2 on 2023-04-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_alter_archivetender_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetender',
            name='tender_name',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='activetender',
            name='winner',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='archivetender',
            name='tender_name',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='archivetender',
            name='winner',
            field=models.CharField(max_length=5000),
        ),
    ]
