# Generated by Django 4.2 on 2023-04-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0007_alter_customer_customer_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activetender',
            name='dk_numbers',
        ),
        migrations.RemoveField(
            model_name='archivetender',
            name='dk_numbers',
        ),
        migrations.AddField(
            model_name='activetender',
            name='dk_numbers',
            field=models.ManyToManyField(to='tenders.dknumber'),
        ),
        migrations.AddField(
            model_name='archivetender',
            name='dk_numbers',
            field=models.ManyToManyField(to='tenders.dknumber'),
        ),
    ]
