# Generated by Django 4.2 on 2023-04-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0008_remove_activetender_dk_numbers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dknumber',
            old_name='number',
            new_name='dk_number',
        ),
    ]
