# Generated by Django 4.2 on 2023-04-13 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenders', '0009_rename_number_dknumber_dk_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='last_name',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriber',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
