# Generated by Django 4.2 on 2023-04-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0010_remove_subscriber_email_remove_subscriber_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedCompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=500)),
                ('shortname', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('primary_activity', models.CharField(max_length=500)),
                ('ceo_name', models.CharField(max_length=500)),
                ('capital', models.FloatField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_contact',
            new_name='customer_person_contact',
        ),
        migrations.RemoveField(
            model_name='activetender',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='archivetender',
            name='winner',
        ),
        migrations.AddField(
            model_name='activetender',
            name='winner_old',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='archivetender',
            name='winner_old',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='activetender',
            name='dk_numbers',
            field=models.ManyToManyField(null=True, to='tenders.dknumber'),
        ),
        migrations.AlterField(
            model_name='activetender',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activetender',
            name='publication_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activetender',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activetender',
            name='tender_name',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='archivetender',
            name='dk_numbers',
            field=models.ManyToManyField(null=True, to='tenders.dknumber'),
        ),
        migrations.AlterField(
            model_name='archivetender',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='archivetender',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archivetender',
            name='tender_name',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.extendedcompanydata'),
        ),
    ]
