# Generated by Django 4.2 on 2023-04-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0011_extendedcompanydata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_name', models.CharField(max_length=500, unique=True)),
                ('winner_edrpou', models.CharField(max_length=100, unique=True)),
                ('winner_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.extendedcompanydata')),
            ],
        ),
        migrations.AddField(
            model_name='activetender',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.winner'),
        ),
        migrations.AddField(
            model_name='archivetender',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.winner'),
        ),
    ]
