# Generated by Django 4.2 on 2023-04-16 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0012_winner_activetender_winner_archivetender_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=10)),
                ('subscriber', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.subscriber')),
            ],
        ),
    ]
