# Generated by Django 4.2 on 2023-04-16 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0013_subscriberbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('subscriber_balance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.subscriberbalance')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('subscriber_balance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.subscriberbalance')),
            ],
        ),
    ]
