# Generated by Django 4.2 on 2023-04-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0015_remove_winner_winner_edrpou'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activetender',
            name='winner_old',
        ),
        migrations.RemoveField(
            model_name='archivetender',
            name='winner_old',
        ),
    ]
