# Generated by Django 4.2 on 2023-04-18 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenders', '0017_rename_subscriber_subscriber_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetender',
            name='dk_numbers',
            field=models.ManyToManyField(to='tenders.dknumber'),
        ),
        migrations.AlterField(
            model_name='archivetender',
            name='dk_numbers',
            field=models.ManyToManyField(to='tenders.dknumber'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriberbalance',
            name='currency',
            field=models.CharField(default='UAH', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriberbalance',
            name='subscriber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenders.subscriber'),
        ),
    ]
