# Generated by Django 4.1.8 on 2023-05-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0018_alter_activetender_dk_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='telegram_user_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
