# Generated by Django 4.1.8 on 2023-05-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0019_subscriber_telegram_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_edrpou',
            new_name='edrpou',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_person_contact',
            new_name='person_contact',
        ),
        migrations.RenameField(
            model_name='dknumber',
            old_name='dk_number',
            new_name='dk',
        ),
        migrations.RenameField(
            model_name='winner',
            old_name='winner_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='winner',
            old_name='winner_name',
            new_name='name',
        ),
    ]
